import type { ProjectRecord } from "./types";

export const PROJECT_SEED: ProjectRecord[] = [
  {
    id: "pr-et",
    initials: "لم",
    gradient: "linear-gradient(135deg,#52525b,#71717a)",
    title: "Easy Touch — Clinic SaaS",
    subtitle: "Najdi AI assistant · WhatsApp · MyFatoorah · LiveKit voice",
    progress: 72,
    badgeClass: "b-green",
    statusKey: "onTrack",
    teamMemberIds: ["tm-yk", "tm-ob"],
    chipKey: "dueAug22",
    phase: "inProgress",
  },
  {
    id: "pr-al",
    initials: "AL",
    gradient: "linear-gradient(135deg,#e6b567,#d99a4e)",
    title: "AutoLog",
    subtitle: "Next.js · Supabase · Teltonika GPS · shared Renter Score",
    progress: 58,
    badgeClass: "b-green",
    statusKey: "onTrack",
    teamMemberIds: ["tm-yk", "tm-ac"],
    chipKey: "product",
    phase: "inProgress",
  },
  {
    id: "pr-sh",
    initials: "SH",
    gradient: "linear-gradient(135deg,#3ecf8e,#2fa876)",
    title: "Shegl Marketplace",
    subtitle: "Gulf technician marketplace · Tap Payments · DigitalOcean",
    progress: 94,
    badgeClass: "b-blue",
    statusKey: "live",
    teamMemberIds: ["tm-ob"],
    chipKey: "maintenance",
    phase: "inProgress",
  },
  {
    id: "pr-mk",
    initials: "MK",
    gradient: "linear-gradient(135deg,#71717a,#3f3f46)",
    title: "Makkah Chamber site",
    subtitle: "RFP under Pixel IT prime · Arabic Dirasat Faniyya",
    progress: 40,
    badgeClass: "b-amber",
    statusKey: "bidStage",
    teamMemberIds: ["tm-yk", "tm-ac"],
    chipKey: "dueJul10",
    chipRose: true,
    phase: "inProgress",
  },
  {
    id: "pr-st",
    initials: "ST",
    gradient: "linear-gradient(135deg,#f2557a,#d63e63)",
    title: "Service Time PWA",
    subtitle: "Field-service PWA for the Saudi market · via Pixel IT",
    progress: 81,
    badgeClass: "b-gold",
    statusKey: "review",
    teamMemberIds: ["tm-ob", "tm-yk"],
    chipKey: "review",
    phase: "review",
  },
  {
    id: "pr-fp",
    initials: "FP",
    gradient: "linear-gradient(135deg,#52525b,#71717a)",
    title: "منصة العائلة · Family Platform",
    subtitle: "11 subsystems · 28-page Arabic proposal · 380K SAR",
    progress: 100,
    badgeClass: "b-blue",
    statusKey: "delivered",
    teamMemberIds: ["tm-yk"],
    chipKey: "delivered",
    phase: "delivered",
  },
];
