import type { ClientRecord } from "./types";

/** Clients de démo — visibles par l'équipe commerciale (Autolog) */
export const SEED_CLIENTS: ClientRecord[] = [
  {
    id: "cl-ilm",
    initials: "IV",
    gradient: "linear-gradient(135deg,#3ecf8e,#52525b)",
    name: "ILM Voyages",
    subtitle: "Location véhicules · flotte AutoLog",
    contact: "Direction flotte",
    marketCode: "MA",
    location: "Marrakech",
    engagement: "Prospect chaud",
    valueAmount: 45000,
    valueCurrency: "MAD",
    statusKey: "prospect",
  },
  {
    id: "cl-atlas",
    initials: "AT",
    gradient: "linear-gradient(135deg,#52525b,#4169d6)",
    name: "Atlas Transport",
    subtitle: "Logistique inter-villes",
    contact: "Service achats",
    marketCode: "MA",
    location: "Casablanca",
    engagement: "Devis en cours",
    valueAmount: 78000,
    valueCurrency: "MAD",
    statusKey: "pending",
  },
  {
    id: "cl-sahara",
    initials: "ST",
    gradient: "linear-gradient(135deg,#e6b567,#d99a4e)",
    name: "Sahara Fleet Services",
    subtitle: "Maintenance parc poids lourds",
    contact: "Dalal · suivi commercial",
    marketCode: "MA",
    location: "Agadir",
    engagement: "Premier contact",
    valueAmount: 32000,
    valueCurrency: "MAD",
    statusKey: "prospect",
  },
];
