import type { ClientRecord } from "./types";

export const SEED_CLIENTS: ClientRecord[] = [
  {
    id: "cl-px",
    initials: "PX",
    gradient: "linear-gradient(135deg,#52525b,#71717a)",
    name: "Pixel IT",
    subtitle: "Prime contractor partner",
    contact: "Operations lead",
    marketCode: "KSA",
    location: "Riyadh",
    engagement: "Subcontract",
    valueAmount: 640000,
    valueCurrency: "SAR",
    statusKey: "partner",
  },
  {
    id: "cl-et",
    initials: "لم",
    gradient: "linear-gradient(135deg,#3ecf8e,#2fa876)",
    name: "Easy Touch · لمسة سهلة",
    subtitle: "Clinic management SaaS",
    contact: "Abu Nasser · Abdulaziz",
    marketCode: "KSA",
    location: "KSA",
    engagement: "Build + phase 2",
    valueAmount: 214000,
    valueCurrency: "SAR",
    statusKey: "active",
  },
  {
    id: "cl-nm",
    initials: "NM",
    gradient: "linear-gradient(135deg,#e6b567,#d99a4e)",
    name: "Natus Marrakech",
    subtitle: "Digital & e-commerce growth",
    contact: "Hayat Ettaki · Paola",
    marketCode: "MA",
    location: "Marrakech",
    engagement: "Retainer",
    valueAmount: 120000,
    valueCurrency: "MAD",
    statusKey: "active",
  },
  {
    id: "cl-sh",
    initials: "SH",
    gradient: "linear-gradient(135deg,#71717a,#3f3f46)",
    name: "Shegl",
    subtitle: "Technician marketplace",
    contact: "Nasser Aleidan",
    marketCode: "KW",
    location: "Kuwait",
    engagement: "Build + support",
    valueAmount: 18500,
    valueCurrency: "KWD",
    statusKey: "active",
  },
  {
    id: "cl-sw",
    initials: "SW",
    gradient: "linear-gradient(135deg,#f2557a,#d63e63)",
    name: "Samnan Water Solutions",
    subtitle: "AI voice support system",
    contact: "Support director",
    marketCode: "KSA",
    location: "KSA",
    engagement: "Proposal",
    valueAmount: 80000,
    valueCurrency: "SAR",
    statusKey: "pending",
  },
  {
    id: "cl-mk",
    initials: "ML",
    gradient: "linear-gradient(135deg,#52525b,#4169d6)",
    name: "Makkah Chamber of Commerce",
    subtitle: "Website redesign RFP",
    contact: "via Pixel IT",
    marketCode: "KSA",
    location: "Makkah",
    engagement: "Bid",
    valueAmount: 410000,
    valueCurrency: "SAR",
    statusKey: "bidStage",
  },
  {
    id: "cl-iv",
    initials: "IV",
    gradient: "linear-gradient(135deg,#3ecf8e,#52525b)",
    name: "ILM Voyages",
    subtitle: "Car rental · AutoLog pilot",
    contact: "Youssef Kaab",
    marketCode: "MA",
    location: "Marrakech",
    engagement: "Internal / pilot",
    valueAmount: null,
    valueCurrency: "MAD",
    statusKey: "pilot",
  },
  {
    id: "cl-ag",
    initials: "AG",
    gradient: "linear-gradient(135deg,#8a90a6,#646b81)",
    name: "Association Aghbalou",
    subtitle: "Education nonprofit",
    contact: "Monsieur Ibrahim",
    marketCode: "MA",
    location: "Morocco",
    engagement: "Design project",
    valueAmount: 24000,
    valueCurrency: "MAD",
    statusKey: "prospect",
  },
];
