import type { EmployeeProfile } from "./types";

const now = new Date().toISOString();

export const HR_SEED: EmployeeProfile[] = [
  {
    memberId: "tm-yk",
    roleTitle: "Founder & Managing Director",
    department: "management",
    contractType: "founder",
    utilization: 92,
    status: "active",
    contractStart: "2022-01-01",
    contractEnd: "",
    entries: [
      {
        id: "hr-e1",
        memberId: "tm-yk",
        type: "bonus",
        date: "2026-06-30",
        amount: 15000,
        currency: "MAD",
        note: "Q2 performance bonus",
        createdAt: now,
      },
      {
        id: "hr-e2",
        memberId: "tm-yk",
        type: "overtime",
        date: "2026-07-05",
        hours: 4,
        note: "Makkah RFP weekend prep",
        createdAt: now,
      },
      {
        id: "hr-e3",
        memberId: "tm-yk",
        type: "leave",
        date: "2026-08-01",
        days: 5,
        note: "Annual leave",
        createdAt: now,
      },
    ],
  },
  {
    memberId: "tm-ob",
    roleTitle: "Developer",
    department: "tech",
    contractType: "cdd",
    utilization: 86,
    status: "active",
    contractStart: "2025-03-01",
    contractEnd: "2026-12-31",
    entries: [
      {
        id: "hr-e4",
        memberId: "tm-ob",
        type: "overtime",
        date: "2026-07-02",
        hours: 6,
        note: "Easy Touch voice pipeline",
        createdAt: now,
      },
      {
        id: "hr-e5",
        memberId: "tm-ob",
        type: "lateness",
        date: "2026-07-07",
        note: "Arrived 25 min late — transport",
        createdAt: now,
      },
      {
        id: "hr-e6",
        memberId: "tm-ob",
        type: "note",
        date: "2026-07-08",
        note: "Strong delivery on medical-scribe module",
        createdAt: now,
      },
    ],
  },
  {
    memberId: "tm-ac",
    roleTitle: "Design Lead",
    department: "design",
    contractType: "core",
    utilization: 74,
    status: "active",
    contractStart: "2024-06-01",
    contractEnd: "",
    entries: [
      {
        id: "hr-e7",
        memberId: "tm-ac",
        type: "bonus",
        date: "2026-06-15",
        amount: 3000,
        currency: "MAD",
        note: "Natus UI delivery",
        createdAt: now,
      },
      {
        id: "hr-e8",
        memberId: "tm-ac",
        type: "leave",
        date: "2026-07-12",
        days: 2,
        note: "Personal leave",
        createdAt: now,
      },
    ],
  },
  {
    memberId: "tm-dl",
    roleTitle: "Commercial / Sales",
    department: "commercial",
    contractType: "commission",
    utilization: 68,
    status: "active",
    contractStart: "2025-01-15",
    contractEnd: "2026-01-14",
    entries: [
      {
        id: "hr-e9",
        memberId: "tm-dl",
        type: "commission",
        date: "2026-06-28",
        amount: 8200,
        currency: "MAD",
        note: "AutoLog deal closed",
        createdAt: now,
      },
      {
        id: "hr-e10",
        memberId: "tm-dl",
        type: "commission",
        date: "2026-07-03",
        amount: 4500,
        currency: "MAD",
        note: "Shegl upsell",
        createdAt: now,
      },
      {
        id: "hr-e11",
        memberId: "tm-dl",
        type: "lateness",
        date: "2026-07-01",
        note: "Client call overrun — 15 min late to standup",
        createdAt: now,
      },
    ],
  },
];
